name: get page

on:
  schedule:
    - cron: '22 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  init-google:
    runs-on: ubuntu-latest
    steps:
      - name: System Time Change
        env:
          TZ: Asia/Shanghai
        run: |
          date
          whoami
          java -version
          javac -version
          python --version
          pip --version
          git --version
          curl --version
          wget --version
      
      - name: Check out repository
        uses: actions/checkout@v3
      #  with:
      #    ref: 20221111GraphPhase  # 指定分支
        env:
          TZ: Asia/Shanghai
      
      - name: Get Page
        env:
          TZ: Asia/Shanghai
        run: |
          #wget https://cn.bing.com/topstories?hl=zh-CN&gl=CN&ceid=CN:zh-Hans >> ./temp/`date +"%Y%m%d%H%M%S"`_zh.html
          curl https://www.chinanews.com.cn/rss/society.xml >> ./temp/`date +"%Y%m%d%H%M%S"`_c_h_i_n_a_n_e_w_s-c_o_m-c_n.xml
          #curl  -H 'Content-Type: application/json' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' https://cn.bing.com/topstories?hl=en-AU&gl=AU&ceid=AU:en >> ./temp/`date +"%Y%m%d%H%M%S"`_au.html
          #curl  -H 'Content-Type: application/json' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' https://rsshub.app/weibo/user/1681213010/0
      
      - name: Execute Submit
        env:
          TZ: Asia/Shanghai
        run: |
          ls -Ali
          du -sh ./*
          git config --global user.name "Code Actions"
          git config --global user.email ${{ secrets.GIT_USERMAIL }}
          git config --list
          git add temp/*
          git commit -m 'new content' -m 'add O Page test.'
          git push origin master
